# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 752)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/act_normal/resources/icon/Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("/* 主窗口背景颜色和字体 */\n"
"QMainWindow {\n"
"    background-color: #f4f6f9;\n"
"    color: #2e3d49;\n"
"    font-family: \"Arial\", sans-serif;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* 标题栏 */\n"
"QLabel#titleLabel {\n"
"    color: #34495e;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* 按钮样式 */\n"
"QPushButton {\n"
"    background-color: #3498db;\n"
"    height:16px;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"    padding: 8px 15px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e6091;\n"
"}\n"
"\n"
"/* LineEdit 样式 */\n"
"QLineEdit {\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #3498db;\n"
"}\n"
"\n"
"/* GroupBox 样式 */\n"
"QGroupBox {\n"
"    margin-top: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 5px;\n"
"    background-color: transparent;\n"
"    color: #2e3d49;\n"
"}\n"
"\n"
"/* 滑块样式 */\n"
"QSlider::groove:horizontal {\n"
"    height: 6px;\n"
"    background: #bdc3c7;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #3498db;\n"
"    border: 1px solid #2980b9;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"/* 下拉框样式 */\n"
"QComboBox {\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #bdc3c7;\n"
"    selection-background-color: #3498db;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QSpinBox{\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"/* 滚动条样式 */\n"
"QScrollBar:vertical {\n"
"    width: 10px;\n"
"    background: #ecf0f1;\n"
"    margin: 0px 3px 0px 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #3498db;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(1000, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 5, 1, 1)
        self.sbox_size = QtWidgets.QSpinBox(self.widget)
        self.sbox_size.setMinimum(1)
        self.sbox_size.setMaximum(40)
        self.sbox_size.setObjectName("sbox_size")
        self.gridLayout_4.addWidget(self.sbox_size, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        self.btn_endDrawing = QtWidgets.QPushButton(self.widget)
        self.btn_endDrawing.setObjectName("btn_endDrawing")
        self.gridLayout_4.addWidget(self.btn_endDrawing, 0, 7, 1, 1)
        self.cbox_penType = QtWidgets.QComboBox(self.widget)
        self.cbox_penType.setObjectName("cbox_penType")
        self.cbox_penType.addItem("")
        self.cbox_penType.addItem("")
        self.cbox_penType.addItem("")
        self.cbox_penType.addItem("")
        self.gridLayout_4.addWidget(self.cbox_penType, 0, 4, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(self.widget)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout_4.addWidget(self.btn_clear, 0, 6, 1, 1)
        self.btn_back = QtWidgets.QPushButton(self.widget)
        self.btn_back.setObjectName("btn_back")
        self.gridLayout_4.addWidget(self.btn_back, 0, 0, 1, 1)
        self.btn_editColor = QtWidgets.QPushButton(self.widget)
        self.btn_editColor.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/act_normal/resources/icon/editColor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_editColor.setIcon(icon1)
        self.btn_editColor.setObjectName("btn_editColor")
        self.gridLayout_4.addWidget(self.btn_editColor, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.widget)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setStyleSheet("border: 2px solid #8f8f91;\n"
"border-radius: 25px;  /* 圆角半径 */\n"
"background-color: white;\n"
"\n"
"")
        self.graphicsView.setRenderHints(QtGui.QPainter.TextAntialiasing)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_4.addWidget(self.graphicsView)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setBaseSize(QtCore.QSize(20, 20))
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_refImg = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_refImg.sizePolicy().hasHeightForWidth())
        self.label_refImg.setSizePolicy(sizePolicy)
        self.label_refImg.setMinimumSize(QtCore.QSize(0, 0))
        self.label_refImg.setMaximumSize(QtCore.QSize(274, 250))
        self.label_refImg.setStyleSheet("border: 2px solid #8f8f91;\n"
"border-radius: 15px;  /* 圆角半径 */\n"
"\n"
"")
        self.label_refImg.setFrameShape(QtWidgets.QFrame.Box)
        self.label_refImg.setAlignment(QtCore.Qt.AlignCenter)
        self.label_refImg.setObjectName("label_refImg")
        self.verticalLayout_3.addWidget(self.label_refImg)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(20, 0, 20, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_voice = QtWidgets.QPushButton(self.widget_2)
        self.btn_voice.setObjectName("btn_voice")
        self.gridLayout.addWidget(self.btn_voice, 0, 0, 1, 2)
        self.ledit_prompt = QtWidgets.QLineEdit(self.widget_2)
        self.ledit_prompt.setStyleSheet("        border: 2px solid #8f8f91;\n"
"        border-radius: 10px;\n"
"        padding: 5px;\n"
"        background-color: #f0f0f0;\n"
"        color: #333;\n"
"        font-size: 14px;")
        self.ledit_prompt.setObjectName("ledit_prompt")
        self.gridLayout.addWidget(self.ledit_prompt, 1, 0, 1, 1)
        self.btn_genImg = QtWidgets.QPushButton(self.widget_2)
        self.btn_genImg.setObjectName("btn_genImg")
        self.gridLayout.addWidget(self.btn_genImg, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_6.addItem(spacerItem2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 0, 1, 1)
        self.btn_saveRefImg = QtWidgets.QPushButton(self.widget_2)
        self.btn_saveRefImg.setObjectName("btn_saveRefImg")
        self.gridLayout_2.addWidget(self.btn_saveRefImg, 1, 1, 1, 1)
        self.btn_saveDraw = QtWidgets.QPushButton(self.widget_2)
        self.btn_saveDraw.setObjectName("btn_saveDraw")
        self.gridLayout_2.addWidget(self.btn_saveDraw, 2, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_6.addItem(spacerItem5)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(20, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rbtn_selfDrawAnalyse = QtWidgets.QRadioButton(self.widget_2)
        self.rbtn_selfDrawAnalyse.setChecked(True)
        self.rbtn_selfDrawAnalyse.setObjectName("rbtn_selfDrawAnalyse")
        self.gridLayout_3.addWidget(self.rbtn_selfDrawAnalyse, 2, 0, 1, 1)
        self.ckbox_camera = QtWidgets.QCheckBox(self.widget_2)
        self.ckbox_camera.setObjectName("ckbox_camera")
        self.gridLayout_3.addWidget(self.ckbox_camera, 0, 0, 1, 1)
        self.ckbox_music = QtWidgets.QCheckBox(self.widget_2)
        self.ckbox_music.setObjectName("ckbox_music")
        self.gridLayout_3.addWidget(self.ckbox_music, 1, 0, 1, 1)
        self.rbtn_refImgAnalyse = QtWidgets.QRadioButton(self.widget_2)
        self.rbtn_refImgAnalyse.setEnabled(False)
        self.rbtn_refImgAnalyse.setCheckable(True)
        self.rbtn_refImgAnalyse.setAutoRepeat(False)
        self.rbtn_refImgAnalyse.setAutoExclusive(True)
        self.rbtn_refImgAnalyse.setObjectName("rbtn_refImgAnalyse")
        self.gridLayout_3.addWidget(self.rbtn_refImgAnalyse, 3, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_2.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.act_editColor = QtWidgets.QAction(MainWindow)
        self.act_editColor.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/act_normal/C:/Users/dell/Desktop/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_editColor.setIcon(icon2)
        self.act_editColor.setObjectName("act_editColor")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EmoVision"))
        self.btn_endDrawing.setText(_translate("MainWindow", "结束绘画"))
        self.cbox_penType.setItemText(0, _translate("MainWindow", "笔"))
        self.cbox_penType.setItemText(1, _translate("MainWindow", "直线"))
        self.cbox_penType.setItemText(2, _translate("MainWindow", "矩形"))
        self.cbox_penType.setItemText(3, _translate("MainWindow", "椭圆"))
        self.btn_clear.setText(_translate("MainWindow", "清空画布"))
        self.btn_back.setText(_translate("MainWindow", "回退"))
        self.btn_editColor.setText(_translate("MainWindow", "编辑颜色"))
        self.groupBox.setTitle(_translate("MainWindow", "参考图像"))
        self.label_refImg.setText(_translate("MainWindow", "目前还未生成图像，快生成一个吧"))
        self.btn_voice.setText(_translate("MainWindow", "语音识别"))
        self.btn_genImg.setText(_translate("MainWindow", "生成图像"))
        self.btn_saveRefImg.setText(_translate("MainWindow", "保存参考图像"))
        self.btn_saveDraw.setText(_translate("MainWindow", "保存绘画"))
        self.rbtn_selfDrawAnalyse.setText(_translate("MainWindow", "个人绘画情感分析"))
        self.ckbox_camera.setText(_translate("MainWindow", "启用摄像头"))
        self.ckbox_music.setText(_translate("MainWindow", "开启音乐"))
        self.rbtn_refImgAnalyse.setText(_translate("MainWindow", "参考图像情感分析"))
        self.act_editColor.setText(_translate("MainWindow", "编辑颜色"))
        self.act_editColor.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">编辑颜色</span></p><p>    从调色板中选择一种颜色。</p></body></html>"))
import QtModules.UI.MainWindow_rc
